create table if not exists public.membership_plans (
  id bigint generated by default as identity primary key,
  label text not null unique,
  price numeric not null check (price > 0),
  description text not null default '',
  audience text not null check (audience in ('boys', 'girls')),
  duration_type text not null check (duration_type in ('monthly', 'day', 'time')),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.payments
  add column if not exists membership_plan_id bigint references public.membership_plans(id) on delete set null;

create or replace function public.set_membership_plans_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_membership_plans_updated_at on public.membership_plans;
create trigger set_membership_plans_updated_at
before update on public.membership_plans
for each row execute function public.set_membership_plans_updated_at();

alter table public.membership_plans enable row level security;

grant select on public.membership_plans to anon, authenticated;
grant insert, update, delete on public.membership_plans to authenticated;
grant usage, select on sequence public.membership_plans_id_seq to authenticated;

drop policy if exists "Active membership plans are public" on public.membership_plans;
create policy "Active membership plans are public"
  on public.membership_plans for select
  using (is_active = true);

drop policy if exists "Admins can view all membership plans" on public.membership_plans;
create policy "Admins can view all membership plans"
  on public.membership_plans for select
  to authenticated
  using (public.is_admin(auth.uid()));

drop policy if exists "Admins can insert membership plans" on public.membership_plans;
create policy "Admins can insert membership plans"
  on public.membership_plans for insert
  to authenticated
  with check (public.is_admin(auth.uid()));

drop policy if exists "Admins can update membership plans" on public.membership_plans;
create policy "Admins can update membership plans"
  on public.membership_plans for update
  to authenticated
  using (public.is_admin(auth.uid()))
  with check (public.is_admin(auth.uid()));

drop policy if exists "Admins can delete membership plans" on public.membership_plans;
create policy "Admins can delete membership plans"
  on public.membership_plans for delete
  to authenticated
  using (public.is_admin(auth.uid()));

insert into public.membership_plans (id, label, price, description, audience, duration_type, sort_order)
values
  (1, 'Boys Monthly Mess (1 Time)', 1300, '1 meal/day access for boys', 'boys', 'monthly', 10),
  (2, 'Girls Monthly Mess (1 Time)', 1000, '1 meal/day access for girls', 'girls', 'monthly', 20),
  (7, 'Boys Monthly Mess (2 Times)', 2200, '2 meals/day access for boys', 'boys', 'monthly', 30),
  (8, 'Girls Monthly Mess (2 Times)', 1600, '2 meals/day access for girls', 'girls', 'monthly', 40),
  (3, 'Boys 1 Day Mess', 120, '24-hour access for boys', 'boys', 'day', 50),
  (4, 'Girls 1 Day Mess', 80, '24-hour access for girls', 'girls', 'day', 60),
  (5, 'Boys 1 Time Mess', 80, 'Single meal choice for boys', 'boys', 'time', 70),
  (6, 'Girls 1 Time Mess', 40, 'Single meal choice for girls', 'girls', 'time', 80)
on conflict (label) do nothing;

select setval(
  pg_get_serial_sequence('public.membership_plans', 'id'),
  greatest((select coalesce(max(id), 1) from public.membership_plans), 1),
  true
);
